
##this script provide simple way to compare odds generated by different frequency dependents models


source("../abc/R/model-slots.R")
update_traits <- function(v, beta) {
  tab <- table(v)
  traits <- names(tab)

  freqs <- as.numeric(tab) / length(v)
  probs <- freqs^(1 - beta)
  probs <- probs / sum(probs)
return(probs)
}

p_prob <- function(p_t, J, u, beta, sde){
  eps <- `if`(sde > 0, rnorm(length(p_t), mean = 0, sd = sde), 0)
  p <- p_t^J * exp(beta*u + eps)
  p_t <- p / sum(p)
  return(p_t)
}



v <- c(rep("A",100),rep("B",10))
table(v)[1]/table(v)[2]

#Youngblood
beta <- -0.012

o=update_traits(v, beta)
o[1]/o[2]


#jcrema min
   b = -0.04 
o=update_traits(v, b)
o[1]/o[2]

#crema max
   b = 0.07
o=update_traits(v, b)

mean(replicate(1000,{
               o=p_prob(table(v)/length(v),sde=1,beta=1.8,J=1.8,u=c(2,1))
               o[1]/o[2]}))


mean(replicate(10000,{
               o=p_prob(table(v)/length(v),sde=1,beta=1.5,J=1.5,u=c(1.05,1))
               o[1]/o[2]}))

mean(replicate(1000,{
               o=p_prob(table(v)/length(v),sde=0,beta=0,J=1.5,u=c(1,1))
               o[1]/o[2]}))
mean(replicate(10000,{
               o=p_prob(table(v)/length(v),sde=1,beta=1.99,J=1.99,u=c(1.05,1))
               o[1]/o[2]}))

mean(replicate(10000,{
               o=p_prob(table(v)/length(v),sde=1,beta=.4,J=.99,u=c(1.05,1))
               o[1]/o[2]}))
